fix adding of blank space on individual NAME
OpenSPP/openg2p-registry pull request #4
Opened 2024-11-15 10:28 UTC by emjay0921

@api.onchange("is_group", "family_name", "given_name", "addl_name")
    def name_change(self):
        vals = {}
        if not self.is_group:
            name = ""
            if self.family_name:
                name += self.family_name + ", "
            if self.given_name:
                name += self.given_name + " "
            if self.addl_name:
                name += self.addl_name + " "
            vals.update({"name": name.upper()})
            self.update(vals)
TO
@api.onchange("is_group", "family_name", "given_name", "addl_name")
    def name_change(self):
        vals = {}
        if not self.is_group:
            name_vals = [
                f"{self.family_name},"
                if self.family_name and self.given_name
                else f"{self.family_name}"
                if self.family_name
                else "",
                self.given_name,
                self.addl_name,
            ]

            name = " ".join(filter(None, name_vals))
            vals.update({"name": name.upper()})
            self.update(vals)

2024-11-18 02:55 UTC, kneckinator requested changes
Thanks for providing a cleaner, faster, and a more Pythonic solution @emjay0921 . :tada:

One thought, however, is related to the `,` (comma) after the family name.
In the `name_change` solution, we will only add the comma after the family name if there is a given name but _not_ if there is only a family_name and an additional name.

See this table:

self.family_name | self.given_name | self.addl_name | Resulting name_vals
-- | -- | -- | --
"Smith" | "John" | "A." | ["Smith,", "John", "A."]
"Smith" | "" | "A." | ["Smith", "", "A."]
"" | "John" | "A." | ["", "John", "A."]
"" | "" | "" | ["", "", ""]

Can you please confirm if this is as expected? The previous code in OpenG2P would always add the comma if there was a `family_name`.

Thanks.

2024-11-18 03:01 UTC, reichie020212 requested changes
@emjay0921 the test `test_01_check_names` in g2p_registry_individual/tests/test_individuals.py also needs an update.

2024-11-19 02:05 UTC, gonzalesedwin1123 approved these changes

2024-11-19 02:12 UTC, reichie020212 approved these changes

2024-11-19 02:26 UTC, kneckinator approved these changes

2024-11-19 02:27 UTC, merged